Repository pimcore/object-merger, pull requests merged in 2024-04, with the labels that each got.

#45 Add CLA check
  .github/workflows/cla.yaml
Labels: Task

#47 Fix translations
  src/Resources/public/js/panel.js
Labels: Bug

#48 [Task]: Update SECURITY.md
  SECURITY.md
Labels: Task, Pimcore:ToDo
